language: node_js
node_js:
  - "10"
  - "12"

script:
  - NODE_ICU_DATA="$(pwd)/node_modules/full-icu"

matrix:
  include:
    - node_js: "10"
      cache:
        directories:
          - node_modules

jobs:
  include:
    - stage: coverage
      node_js: "10"
      script: npm run codecov
